import type { Metadata } from "next";
import "../globals.css";
import inter from "@/constants/localFont";
import { Toaster } from "react-hot-toast";
import Providers from "../Providers";
import Header from "../Header";

export const metadata: Metadata = {
  title: "Next Shop Panel",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" dir="ltr">
      <body
        suppressHydrationWarning={true}
        className={`${inter.className} min-h-screen font-sans`}
      >
        <Providers>
          <Toaster />
          <Header />
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 xl:max-w-screen-xl">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
